"""Generating ``runlace_types/``.

One ``.pyi`` per connector, a ``Ctx`` class tying them together, and a package
``__init__``. These stubs are what pyright checks workflow code against, so
they are the whole reason D3's typecheck stage can catch an unknown tool or a
misspelled keyword argument before anything runs.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .jsonschema_py import Field, TypeRenderer, indent_docstring
from .naming import class_name
from .paths import RunlacePaths

HEADER = "# Generated by runlace. Do not edit -- run `runlace sync` instead.\n"


@dataclass
class ToolSpec:
    """A discovered tool, in the shape stub generation needs."""

    name: str
    method: str
    description: str | None
    input_schema: dict[str, Any] | None
    output_schema: dict[str, Any] | None
    risk: str


@dataclass
class ConnectorSpec:
    name: str
    attr: str
    tools: list[ToolSpec] = field(default_factory=list[ToolSpec])

    @property
    def class_name(self) -> str:
        return class_name(self.attr)


@dataclass
class GeneratedStubs:
    files: list[Path]
    warnings: list[str]


def _signature(fields: list[Field]) -> str:
    if not fields:
        return "self"
    parts = ["self", "*"]
    for f in fields:
        parts.append(f"{f.py_name}: {f.type_expr}" + ("" if f.required else " = ..."))
    return ", ".join(parts)


def _method_doc(tool: ToolSpec, fields: list[Field]) -> str:
    lines: list[str] = [(tool.description or tool.name).strip()]
    renamed = [f for f in fields if f.renamed]
    if renamed:
        lines.append("")
        for f in renamed:
            lines.append(f'{f.py_name} maps to the JSON key "{f.json_key}".')
    lines.append("")
    lines.append(f"(risk: {tool.risk})")
    return "\n".join(lines)


def render_connector_stub(connector: ConnectorSpec) -> tuple[str, list[str]]:
    """Render one ``connectors/<name>.pyi``. Returns ``(source, warnings)``."""
    renderer = TypeRenderer()
    warnings: list[str] = []
    methods: list[str] = []

    for tool in connector.tools:
        hint = class_name(tool.method)
        shape = renderer.object_fields(tool.input_schema, hint)
        if shape.unmappable is not None:
            warnings.append(
                f"{connector.name}.{tool.name}: parameter {shape.unmappable!r} cannot be a "
                f"Python keyword argument, tool omitted from the stubs"
            )
            continue

        if shape.fields:
            renderer.add_typed_dict(f"{hint}Input", shape.fields)

        return_type = (
            renderer.render(tool.output_schema, f"{hint}Output")
            if tool.output_schema
            else "object"
        )

        methods.append(
            "\n".join(
                [
                    f"    def {tool.method}({_signature(shape.fields)}) -> {return_type}:",
                    indent_docstring(_method_doc(tool, shape.fields), "        "),
                    "        ...",
                ]
            )
        )

    parts = [HEADER, f"# Connector: {connector.name}\n"]
    if renderer.typing_imports:
        names = ", ".join(sorted(renderer.typing_imports))
        parts.append(f"\nfrom typing import {names}\n")
    for block in renderer.blocks:
        parts.append("\n" + block + "\n")
    parts.append(f"\nclass {connector.class_name}:\n")
    parts.append("\n\n".join(methods) + "\n" if methods else "    ...\n")

    return "".join(parts), warnings


def render_ctx_stub(connectors: list[ConnectorSpec]) -> str:
    parts = [HEADER, "\n"]
    for c in connectors:
        parts.append(f"from .connectors.{c.attr} import {c.class_name}\n")
    parts.append("\nclass Ctx:\n")
    parts.append(indent_docstring(CTX_DOC, "    ") + "\n\n")
    parts.append("    inputs: dict[str, object]\n")
    for c in connectors:
        parts.append(f"    {c.attr}: {c.class_name}\n")
    return "".join(parts)


CTX_DOC = """What a workflow receives.

Call tools as ctx.<connector>.<tool>(**kwargs). Use static attribute access
only -- getattr(ctx, name) is rejected at create time.
"""


def render_init_stub() -> str:
    return HEADER + "\nfrom .ctx import Ctx as Ctx\n\n__all__ = [\"Ctx\"]\n"


def generate(paths: RunlacePaths, connectors: list[ConnectorSpec]) -> GeneratedStubs:
    """Write the whole ``runlace_types/`` tree, replacing what was there."""
    paths.create()

    for stale in paths.connectors.glob("*.pyi"):
        stale.unlink()

    written: list[Path] = []
    warnings: list[str] = []

    def write(path: Path, source: str) -> None:
        path.write_text(source, encoding="utf-8")
        written.append(path)

    write(paths.types / "__init__.pyi", render_init_stub())
    write(paths.connectors / "__init__.pyi", HEADER)

    for connector in connectors:
        source, connector_warnings = render_connector_stub(connector)
        warnings.extend(connector_warnings)
        write(paths.connectors / f"{connector.attr}.pyi", source)

    write(paths.types / "ctx.pyi", render_ctx_stub(connectors))
    return GeneratedStubs(files=written, warnings=warnings)
