"""Generating ``runlace_types/``.

One ``.pyi`` per connector, a ``Ctx`` class tying them together, and a package
``__init__``. These stubs are what pyright checks workflow code against, so
they are the whole reason D3's typecheck stage can catch an unknown tool or a
misspelled keyword argument before anything runs.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .jsonschema_py import Field, TypeRenderer, indent_docstring
from .naming import class_name
from .paths import RunlacePaths

HEADER = "# Generated by runlace. Do not edit -- run `runlace sync` instead.\n"


@dataclass
class ToolSpec:
    """A discovered tool, in the shape stub generation needs."""

    name: str
    method: str
    description: str | None
    input_schema: dict[str, Any] | None
    output_schema: dict[str, Any] | None
    risk: str


@dataclass
class ConnectorSpec:
    name: str
    attr: str
    tools: list[ToolSpec] = field(default_factory=list[ToolSpec])

    @property
    def class_name(self) -> str:
        return class_name(self.attr)


@dataclass
class GeneratedStubs:
    files: list[Path]
    warnings: list[str]


def _signature(fields: list[Field]) -> str:
    if not fields:
        return "self"
    parts = ["self", "*"]
    for f in fields:
        parts.append(f"{f.py_name}: {f.type_expr}" + ("" if f.required else " = ..."))
    return ", ".join(parts)


def _method_doc(tool: ToolSpec, fields: list[Field]) -> str:
    lines: list[str] = [(tool.description or tool.name).strip()]
    renamed = [f for f in fields if f.renamed]
    if renamed:
        lines.append("")
        for f in renamed:
            lines.append(f'{f.py_name} maps to the JSON key "{f.json_key}".')
    lines.append("")
    lines.append(f"(risk: {tool.risk})")
    return "\n".join(lines)


def render_connector_stub(connector: ConnectorSpec) -> tuple[str, list[str]]:
    """Render one ``connectors/<name>.pyi``. Returns ``(source, warnings)``."""
    renderer = TypeRenderer()
    warnings: list[str] = []
    methods: list[str] = []

    for tool in connector.tools:
        hint = class_name(tool.method)
        shape = renderer.object_fields(tool.input_schema, hint)
        if shape.unmappable is not None:
            warnings.append(
                f"{connector.name}.{tool.name}: parameter {shape.unmappable!r} cannot be a "
                f"Python keyword argument, tool omitted from the stubs"
            )
            continue

        # No `<Tool>Input` TypedDict. Arguments are keyword-only and the
        # signature spells every one of them out, so an aggregate of the same
        # fields is unreachable: workflow code cannot even import it (see the
        # `stub-submodule-import` lint). It was a third of what `get_tools`
        # sends an agent to read. Types *nested* inside a parameter are a
        # different matter -- the signature names those, and the renderer emits
        # them on its own.

        if tool.output_schema:
            return_type = renderer.render(tool.output_schema, f"{hint}Output")
        else:
            # D2 derives return types from the schemas; with no output schema
            # there is nothing to derive, and `Any` is how that is spelled.
            # `object` would read as stricter but is not: it forces the author
            # to write `cast(dict[str, object], ...)` to touch the value, and
            # that cast is an unchecked promise where `Any` is an admitted
            # unknown. See `runlace.sessions.tool_payload` for what actually
            # arrives.
            return_type = "Any"
            renderer.typing_imports.add("Any")

        methods.append(
            "\n".join(
                [
                    f"    def {tool.method}({_signature(shape.fields)}) -> {return_type}:",
                    indent_docstring(_method_doc(tool, shape.fields), "        "),
                    "        ...",
                ]
            )
        )

    parts = [HEADER, f"# Connector: {connector.name}\n"]
    if renderer.typing_imports:
        names = ", ".join(sorted(renderer.typing_imports))
        parts.append(f"\nfrom typing import {names}\n")
    for block in renderer.blocks:
        parts.append("\n" + block + "\n")
    parts.append(f"\nclass {connector.class_name}:\n")
    parts.append("\n\n".join(methods) + "\n" if methods else "    ...\n")

    return "".join(parts), warnings


def render_ctx_stub(connectors: list[ConnectorSpec]) -> str:
    parts = [HEADER, "\nfrom ._workflow import Inputs\n"]
    for c in connectors:
        parts.append(f"from .connectors.{c.attr} import {c.class_name}\n")
    parts.append("\nclass Ctx:\n")
    parts.append(indent_docstring(CTX_DOC, "    ") + "\n\n")
    parts.append("    inputs: Inputs\n")
    for c in connectors:
        parts.append(f"    {c.attr}: {c.class_name}\n")
    return "".join(parts)


CTX_DOC = """What a workflow receives.

Call tools as ctx.<connector>.<tool>(**kwargs). Use static attribute access
only -- getattr(ctx, name) is rejected at create time.
"""


WORKFLOW_TYPES_STUB = "_workflow.pyi"

_WORKFLOW_TYPES_DOC = (
    "# Per-workflow types (D7). The definitions here are the permissive fallback\n"
    "# your editor sees; `create_workflow` regenerates this module with `Inputs`\n"
    "# and `Output` narrowed to the schemas the workflow declared, and typechecks\n"
    "# against that.\n"
)


def render_workflow_types_fallback() -> str:
    """The ``_workflow.pyi`` that ships in ``runlace_types/`` after discovery."""
    return (
        HEADER
        + _WORKFLOW_TYPES_DOC
        + "\nfrom typing import TypeAlias\n"
        + "\nInputs: TypeAlias = dict[str, object]\n"
        + "Output: TypeAlias = dict[str, object]\n"
    )


def render_workflow_types(
    inputs_schema: dict[str, Any] | None,
    outputs_schema: dict[str, Any] | None,
) -> str:
    """The ``_workflow.pyi`` used while compiling one workflow.

    ``Inputs`` and ``Output`` are written with the functional ``TypedDict``
    syntax because both are subscripted or built with the raw JSON key --
    ``ctx.inputs["from"]``, ``return {"count": n}``. Unlike a tool's keyword
    arguments, the keys are never renamed, so reserved words are not a problem.
    """
    renderer = TypeRenderer()
    declarations: list[str] = []
    aliases = False

    inputs = _typed_dict_declaration(renderer, "Inputs", inputs_schema, "Input")
    if inputs is None:
        inputs, aliases = "Inputs: TypeAlias = dict[str, object]", True
    declarations.append(inputs)

    if outputs_schema is None:
        declarations.append("Output: TypeAlias = dict[str, object]")
        aliases = True
    else:
        output = _typed_dict_declaration(renderer, "Output", outputs_schema, "Output")
        if output is None:
            # Not an object schema -- a list, a scalar, a union. A plain alias
            # says the same thing.
            expr = renderer.render(outputs_schema, "OutputValue", _defs(outputs_schema))
            output, aliases = f"Output: TypeAlias = {expr}", True
        declarations.append(output)

    imports = set(renderer.typing_imports)
    if aliases:
        imports.add("TypeAlias")

    parts = [HEADER, _WORKFLOW_TYPES_DOC]
    if imports:
        parts.append(f"\nfrom typing import {', '.join(sorted(imports))}\n")
    for block in renderer.blocks:
        parts.append("\n" + block + "\n")
    for declaration in declarations:
        parts.append("\n" + declaration + "\n")
    return "".join(parts)


def _defs(schema: dict[str, Any]) -> dict[str, Any]:
    merged: dict[str, Any] = {}
    for key in ("$defs", "definitions"):
        local = schema.get(key)
        if isinstance(local, dict):
            merged.update(local)
    return merged


def _typed_dict_declaration(
    renderer: TypeRenderer, name: str, schema: Any, hint: str
) -> str | None:
    """Render ``Name = TypedDict(...)``, or ``None`` if the schema is not an object."""
    if not isinstance(schema, dict):
        return None
    if schema.get("type") not in (None, "object"):
        return None
    properties = schema.get("properties")
    if properties is not None and not isinstance(properties, dict):
        return None
    if properties is None and schema.get("type") != "object":
        return None

    required = schema.get("required")
    required_keys = set(required) if isinstance(required, list) else set()
    defs = _defs(schema)

    renderer.typing_imports.add("TypedDict")
    entries: list[str] = []
    for key, subschema in (properties or {}).items():
        expr = renderer.render(subschema, f"{hint}{class_name(str(key))}", defs)
        if str(key) not in required_keys:
            renderer.typing_imports.add("NotRequired")
            expr = f"NotRequired[{expr}]"
        entries.append(f"    {str(key)!r}: {expr},")

    if not entries:
        return f'{name} = TypedDict("{name}", {{}})'
    body = "\n".join(entries)
    return f'{name} = TypedDict("{name}", {{\n{body}\n}})'


def render_init_stub() -> str:
    return (
        HEADER
        + "\nfrom ._workflow import Inputs as Inputs, Output as Output\n"
        + "from .ctx import Ctx as Ctx\n"
        + '\n__all__ = ["Ctx", "Inputs", "Output"]\n'
    )


def generate(paths: RunlacePaths, connectors: list[ConnectorSpec]) -> GeneratedStubs:
    """Write the whole ``runlace_types/`` tree, replacing what was there."""
    paths.create()

    for stale in paths.connectors.glob("*.pyi"):
        stale.unlink()

    written: list[Path] = []
    warnings: list[str] = []

    def write(path: Path, source: str) -> None:
        path.write_text(source, encoding="utf-8")
        written.append(path)

    write(paths.types / "__init__.pyi", render_init_stub())
    write(paths.types / WORKFLOW_TYPES_STUB, render_workflow_types_fallback())
    write(paths.connectors / "__init__.pyi", HEADER)

    for connector in connectors:
        source, connector_warnings = render_connector_stub(connector)
        warnings.extend(connector_warnings)
        write(paths.connectors / f"{connector.attr}.pyi", source)

    write(paths.types / "ctx.pyi", render_ctx_stub(connectors))
    return GeneratedStubs(files=written, warnings=warnings)
